

# Introduction  

This navigation guide will introduce the options within the Trelliscope viewer and how to use them.  For information on creating a Trelliscope viewer see the [tutorial](http://tessera.io/docs-trelliscope/#introduction). 

Trelliscope is a visualization tool that provides interactive exploration of large collections of plots. Trelliscope enables detailed, flexible visualization of large data sets by partitioning data into subsets, applying a plot method to each subset to create a panel, and then allowing the analyst to interactively view the panels. Interaction is provided by the ability to sort and filter the panels based on metrics computed for each subset that describe behaviors of interest. These metrics are called cognostics

In addition, Trelliscope results can be easily shared with other researchers in a way that they can view and interact with.

**Examples:**
Throughout this guide there will be example screenshots.  If you would like to follow along, the Trelliscope viewer that created these examples can be found [here](https://ascm.shinyapps.io/amw-power/).  This viewer was created with a dataset that contains recordings of the energy consumption and outdoor air temperature of four retail buildings at various locations in the U.S. at 15 min. intervals during 2010.